package com.example.nydp.entity;

import javax.persistence.*;
import java.util.Date;

@Entity
@Table(name = "realtimedateinfo")
public class RealTimeDateInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column realtimedateinfo.realTimeId
     *
     * @mbggenerated
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "realtimeid")
    private Long realtimeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column realtimedateinfo.terminalId
     *
     * @mbggenerated
     */
    @Column(name = "terminalid")
    private Long terminalid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column realtimedateinfo.terminalNo
     *
     * @mbggenerated
     */
    @Column(name = "terminalno")
    private String terminalno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column realtimedateinfo.terminalName
     *
     * @mbggenerated
     */
    @Column(name = "terminalname")
    private String terminalname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column realtimedateinfo.updateDate
     *
     * @mbggenerated
     */
    @Column(name = "updatedate")
    private Date updatedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column realtimedateinfo.ad1
     *
     * @mbggenerated
     */
    @Column(name = "ad1")
    private String ad1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column realtimedateinfo.ad2
     *
     * @mbggenerated
     */
    @Column(name = "ad2")
    private String ad2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column realtimedateinfo.ad3
     *
     * @mbggenerated
     */
    @Column(name = "ad3")
    private String ad3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column realtimedateinfo.ad4
     *
     * @mbggenerated
     */
    @Column(name = "ad4")
    private String ad4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column realtimedateinfo.ad5
     *
     * @mbggenerated
     */
    @Column(name = "ad5")
    private String ad5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column realtimedateinfo.ad6
     *
     * @mbggenerated
     */
    @Column(name = "ad6")
    private String ad6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column realtimedateinfo.ad7
     *
     * @mbggenerated
     */
    @Column(name = "ad7")
    private String ad7;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column realtimedateinfo.ad8
     *
     * @mbggenerated
     */
    @Column(name = "ad8")
    private String ad8;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column realtimedateinfo.ad9
     *
     * @mbggenerated
     */
    @Column(name = "ad9")
    private String ad9;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column realtimedateinfo.ad10
     *
     * @mbggenerated
     */
    @Column(name = "ad10")
    private String ad10;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column realtimedateinfo.k1
     *
     * @mbggenerated
     */
    @Column(name = "k1")
    private Integer k1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column realtimedateinfo.k2
     *
     * @mbggenerated
     */
    @Column(name = "k2")
    private Integer k2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column realtimedateinfo.k3
     *
     * @mbggenerated
     */
    @Column(name = "k3")
    private Integer k3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column realtimedateinfo.k4
     *
     * @mbggenerated
     */
    @Column(name = "k4")
    private Integer k4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column realtimedateinfo.k5
     *
     * @mbggenerated
     */
    @Column(name = "k5")
    private Integer k5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column realtimedateinfo.k6
     *
     * @mbggenerated
     */
    @Column(name = "k6")
    private Integer k6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column realtimedateinfo.k7
     *
     * @mbggenerated
     */
    @Column(name = "k7")
    private Integer k7;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column realtimedateinfo.k8
     *
     * @mbggenerated
     */
    @Column(name = "k8")
    private Integer k8;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column realtimedateinfo.k9
     *
     * @mbggenerated
     */
    @Column(name = "k9")
    private Integer k9;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column realtimedateinfo.k10
     *
     * @mbggenerated
     */
    @Column(name = "k10")
    private Integer k10;


    public Long getRealtimeid() {
        return realtimeid;
    }

    public void setRealtimeid(Long realtimeid) {
        this.realtimeid = realtimeid;
    }

    public Long getTerminalid() {
        return terminalid;
    }

    public void setTerminalid(Long terminalid) {
        this.terminalid = terminalid;
    }

    public String getTerminalno() {
        return terminalno;
    }

    public void setTerminalno(String terminalno) {
        this.terminalno = terminalno;
    }

    public String getTerminalname() {
        return terminalname;
    }

    public void setTerminalname(String terminalname) {
        this.terminalname = terminalname;
    }

    public Date getUpdatedate() {
        return updatedate;
    }

    public void setUpdatedate(Date updatedate) {
        this.updatedate = updatedate;
    }

    public String getAd1() {
        return ad1;
    }

    public void setAd1(String ad1) {
        this.ad1 = ad1;
    }

    public String getAd2() {
        return ad2;
    }

    public void setAd2(String ad2) {
        this.ad2 = ad2;
    }

    public String getAd3() {
        return ad3;
    }

    public void setAd3(String ad3) {
        this.ad3 = ad3;
    }

    public String getAd4() {
        return ad4;
    }

    public void setAd4(String ad4) {
        this.ad4 = ad4;
    }

    public String getAd5() {
        return ad5;
    }

    public void setAd5(String ad5) {
        this.ad5 = ad5;
    }

    public String getAd6() {
        return ad6;
    }

    public void setAd6(String ad6) {
        this.ad6 = ad6;
    }

    public String getAd7() {
        return ad7;
    }

    public void setAd7(String ad7) {
        this.ad7 = ad7;
    }

    public String getAd8() {
        return ad8;
    }

    public void setAd8(String ad8) {
        this.ad8 = ad8;
    }

    public String getAd9() {
        return ad9;
    }

    public void setAd9(String ad9) {
        this.ad9 = ad9;
    }

    public String getAd10() {
        return ad10;
    }

    public void setAd10(String ad10) {
        this.ad10 = ad10;
    }

    public Integer getK1() {
        return k1;
    }

    public void setK1(Integer k1) {
        this.k1 = k1;
    }

    public Integer getK2() {
        return k2;
    }

    public void setK2(Integer k2) {
        this.k2 = k2;
    }

    public Integer getK3() {
        return k3;
    }

    public void setK3(Integer k3) {
        this.k3 = k3;
    }

    public Integer getK4() {
        return k4;
    }

    public void setK4(Integer k4) {
        this.k4 = k4;
    }

    public Integer getK5() {
        return k5;
    }

    public void setK5(Integer k5) {
        this.k5 = k5;
    }

    public Integer getK6() {
        return k6;
    }

    public void setK6(Integer k6) {
        this.k6 = k6;
    }

    public Integer getK7() {
        return k7;
    }

    public void setK7(Integer k7) {
        this.k7 = k7;
    }

    public Integer getK8() {
        return k8;
    }

    public void setK8(Integer k8) {
        this.k8 = k8;
    }

    public Integer getK9() {
        return k9;
    }

    public void setK9(Integer k9) {
        this.k9 = k9;
    }

    public Integer getK10() {
        return k10;
    }

    public void setK10(Integer k10) {
        this.k10 = k10;
    }
}