package com.example.nydp.entity;

import javax.persistence.*;

@Entity
@Table(name = "terminal_info")
public class TerminalInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column terminal_info.Terminal_ID
     *
     * @mbggenerated
     */
    @Id
    @GeneratedValue
    @Column(name = "terminal_Id")
    private Long terminalId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column terminal_info.Terminal_CommunicationID
     *
     * @mbggenerated
     */
    @Column(name = "terminal_Communicationid")
    private String terminalCommunicationid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column terminal_info.Terminal_SimCardID
     *
     * @mbggenerated
     */
    @Column(name = "terminal_Simcardid")
    private Long terminalSimcardid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column terminal_info.Terminal_OrgID
     *
     * @mbggenerated
     */
    @Column(name = "terminal_Orgid")
    private Long terminalOrgid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column terminal_info.terminalName
     *
     * @mbggenerated
     */
    @Column(name = "terminalname")
    private String terminalname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column terminal_info.remarks
     *
     * @mbggenerated
     */
    @Column(name = "remarks")
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column terminal_info.latitude
     *
     * @mbggenerated
     */
    @Column(name = "latitude")
    private Double latitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column terminal_info.longitude
     *
     * @mbggenerated
     */
    @Column(name = "longitude")
    private Double longitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column terminal_info.address
     *
     * @mbggenerated
     */
    @Column(name = "address")
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column terminal_info.videoNo
     *
     * @mbggenerated
     */
    @Column(name = "videono")
    private String videono;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column terminal_info.enabled
     *
     * @mbggenerated
     */
    @Column(name = "enabled")
    private Integer enabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column terminal_info.penghuturangshiduDown
     *
     * @mbggenerated
     */
    @Column(name = "penghuturangshidudown")
    private Double penghuturangshidudown;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column terminal_info.penghuturangshiduUp
     *
     * @mbggenerated
     */
    @Column(name = "penghuturangshiduup")
    private Double penghuturangshiduup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column terminal_info.penghuturangwenduDown
     *
     * @mbggenerated
     */
    @Column(name = "penghuturangwendudown")
    private Double penghuturangwendudown;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column terminal_info.penghuturangwenduUp
     *
     * @mbggenerated
     */
    @Column(name = "penghuturangwenduup")
    private Double penghuturangwenduup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column terminal_info.penghukongqishiduDown
     *
     * @mbggenerated
     */
    @Column(name = "penghukongqishidudown")
    private Double penghukongqishidudown;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column terminal_info.penghukongqishiduUp
     *
     * @mbggenerated
     */
    @Column(name = "penghukongqishiduup")
    private Double penghukongqishiduup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column terminal_info.penghukongqiwenduDown
     *
     * @mbggenerated
     */
    @Column(name = "penghukongqiwendudown")
    private Double penghukongqiwendudown;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column terminal_info.penghukongqiwenduUp
     *
     * @mbggenerated
     */
    @Column(name = "penghukongqiwenduup")
    private Double penghukongqiwenduup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column terminal_info.changquyuliangDown
     *
     * @mbggenerated
     */
    @Column(name = "changquyuliangdown")
    private Double changquyuliangdown;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column terminal_info.changquyuliangUp
     *
     * @mbggenerated
     */
    @Column(name = "changquyuliangup")
    private Double changquyuliangup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column terminal_info.changqufengsuDown
     *
     * @mbggenerated
     */
    @Column(name = "changqufengsudown")
    private Double changqufengsudown;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column terminal_info.changqufengsuUp
     *
     * @mbggenerated
     */
    @Column(name = "changqufengsuup")
    private Double changqufengsuup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column terminal_info.changqufengliDown
     *
     * @mbggenerated
     */
    @Column(name = "changqufenglidown")
    private Double changqufenglidown;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column terminal_info.changqufengliUp
     *
     * @mbggenerated
     */
    @Column(name = "changqufengliup")
    private Double changqufengliup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column terminal_info.changqushiduDown
     *
     * @mbggenerated
     */
    @Column(name = "changqushidudown")
    private Double changqushidudown;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column terminal_info.changqushiduUp
     *
     * @mbggenerated
     */
    @Column(name = "changqushiduup")
    private Double changqushiduup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column terminal_info.changquwenduDown
     *
     * @mbggenerated
     */
    @Column(name = "changquwendudown")
    private Double changquwendudown;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column terminal_info.changquwenduUp
     *
     * @mbggenerated
     */
    @Column(name = "changquwenduup")
    private Double changquwenduup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column terminal_info.deviceSerial
     *
     * @mbggenerated
     */
    @Column(name = "deviceserial")
    private String deviceserial;

    @Column(name = "zuowu")
    private String zuowu;

    public String getZuowu() {
        return zuowu;
    }

    public void setZuowu(String zuowu) {
        this.zuowu = zuowu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column terminal_info.Terminal_ID
     *
     * @return the value of terminal_info.Terminal_ID
     *
     * @mbggenerated
     */
    public Long getTerminalId() {
        return terminalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column terminal_info.Terminal_ID
     *
     * @param terminalId the value for terminal_info.Terminal_ID
     *
     * @mbggenerated
     */
    public void setTerminalId(Long terminalId) {
        this.terminalId = terminalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column terminal_info.Terminal_CommunicationID
     *
     * @return the value of terminal_info.Terminal_CommunicationID
     *
     * @mbggenerated
     */
    public String getTerminalCommunicationid() {
        return terminalCommunicationid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column terminal_info.Terminal_CommunicationID
     *
     * @param terminalCommunicationid the value for terminal_info.Terminal_CommunicationID
     *
     * @mbggenerated
     */
    public void setTerminalCommunicationid(String terminalCommunicationid) {
        this.terminalCommunicationid = terminalCommunicationid == null ? null : terminalCommunicationid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column terminal_info.Terminal_SimCardID
     *
     * @return the value of terminal_info.Terminal_SimCardID
     *
     * @mbggenerated
     */
    public Long getTerminalSimcardid() {
        return terminalSimcardid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column terminal_info.Terminal_SimCardID
     *
     * @param terminalSimcardid the value for terminal_info.Terminal_SimCardID
     *
     * @mbggenerated
     */
    public void setTerminalSimcardid(Long terminalSimcardid) {
        this.terminalSimcardid = terminalSimcardid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column terminal_info.Terminal_OrgID
     *
     * @return the value of terminal_info.Terminal_OrgID
     *
     * @mbggenerated
     */
    public Long getTerminalOrgid() {
        return terminalOrgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column terminal_info.Terminal_OrgID
     *
     * @param terminalOrgid the value for terminal_info.Terminal_OrgID
     *
     * @mbggenerated
     */
    public void setTerminalOrgid(Long terminalOrgid) {
        this.terminalOrgid = terminalOrgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column terminal_info.terminalName
     *
     * @return the value of terminal_info.terminalName
     *
     * @mbggenerated
     */
    public String getTerminalname() {
        return terminalname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column terminal_info.terminalName
     *
     * @param terminalname the value for terminal_info.terminalName
     *
     * @mbggenerated
     */
    public void setTerminalname(String terminalname) {
        this.terminalname = terminalname == null ? null : terminalname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column terminal_info.remarks
     *
     * @return the value of terminal_info.remarks
     *
     * @mbggenerated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column terminal_info.remarks
     *
     * @param remarks the value for terminal_info.remarks
     *
     * @mbggenerated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column terminal_info.latitude
     *
     * @return the value of terminal_info.latitude
     *
     * @mbggenerated
     */
    public Double getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column terminal_info.latitude
     *
     * @param latitude the value for terminal_info.latitude
     *
     * @mbggenerated
     */
    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column terminal_info.longitude
     *
     * @return the value of terminal_info.longitude
     *
     * @mbggenerated
     */
    public Double getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column terminal_info.longitude
     *
     * @param longitude the value for terminal_info.longitude
     *
     * @mbggenerated
     */
    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column terminal_info.address
     *
     * @return the value of terminal_info.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column terminal_info.address
     *
     * @param address the value for terminal_info.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column terminal_info.videoNo
     *
     * @return the value of terminal_info.videoNo
     *
     * @mbggenerated
     */
    public String getVideono() {
        return videono;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column terminal_info.videoNo
     *
     * @param videono the value for terminal_info.videoNo
     *
     * @mbggenerated
     */
    public void setVideono(String videono) {
        this.videono = videono == null ? null : videono.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column terminal_info.enabled
     *
     * @return the value of terminal_info.enabled
     *
     * @mbggenerated
     */
    public Integer getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column terminal_info.enabled
     *
     * @param enabled the value for terminal_info.enabled
     *
     * @mbggenerated
     */
    public void setEnabled(Integer enabled) {
        this.enabled = enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column terminal_info.penghuturangshiduDown
     *
     * @return the value of terminal_info.penghuturangshiduDown
     *
     * @mbggenerated
     */
    public Double getPenghuturangshidudown() {
        return penghuturangshidudown;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column terminal_info.penghuturangshiduDown
     *
     * @param penghuturangshidudown the value for terminal_info.penghuturangshiduDown
     *
     * @mbggenerated
     */
    public void setPenghuturangshidudown(Double penghuturangshidudown) {
        this.penghuturangshidudown = penghuturangshidudown;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column terminal_info.penghuturangshiduUp
     *
     * @return the value of terminal_info.penghuturangshiduUp
     *
     * @mbggenerated
     */
    public Double getPenghuturangshiduup() {
        return penghuturangshiduup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column terminal_info.penghuturangshiduUp
     *
     * @param penghuturangshiduup the value for terminal_info.penghuturangshiduUp
     *
     * @mbggenerated
     */
    public void setPenghuturangshiduup(Double penghuturangshiduup) {
        this.penghuturangshiduup = penghuturangshiduup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column terminal_info.penghuturangwenduDown
     *
     * @return the value of terminal_info.penghuturangwenduDown
     *
     * @mbggenerated
     */
    public Double getPenghuturangwendudown() {
        return penghuturangwendudown;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column terminal_info.penghuturangwenduDown
     *
     * @param penghuturangwendudown the value for terminal_info.penghuturangwenduDown
     *
     * @mbggenerated
     */
    public void setPenghuturangwendudown(Double penghuturangwendudown) {
        this.penghuturangwendudown = penghuturangwendudown;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column terminal_info.penghuturangwenduUp
     *
     * @return the value of terminal_info.penghuturangwenduUp
     *
     * @mbggenerated
     */
    public Double getPenghuturangwenduup() {
        return penghuturangwenduup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column terminal_info.penghuturangwenduUp
     *
     * @param penghuturangwenduup the value for terminal_info.penghuturangwenduUp
     *
     * @mbggenerated
     */
    public void setPenghuturangwenduup(Double penghuturangwenduup) {
        this.penghuturangwenduup = penghuturangwenduup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column terminal_info.penghukongqishiduDown
     *
     * @return the value of terminal_info.penghukongqishiduDown
     *
     * @mbggenerated
     */
    public Double getPenghukongqishidudown() {
        return penghukongqishidudown;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column terminal_info.penghukongqishiduDown
     *
     * @param penghukongqishidudown the value for terminal_info.penghukongqishiduDown
     *
     * @mbggenerated
     */
    public void setPenghukongqishidudown(Double penghukongqishidudown) {
        this.penghukongqishidudown = penghukongqishidudown;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column terminal_info.penghukongqishiduUp
     *
     * @return the value of terminal_info.penghukongqishiduUp
     *
     * @mbggenerated
     */
    public Double getPenghukongqishiduup() {
        return penghukongqishiduup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column terminal_info.penghukongqishiduUp
     *
     * @param penghukongqishiduup the value for terminal_info.penghukongqishiduUp
     *
     * @mbggenerated
     */
    public void setPenghukongqishiduup(Double penghukongqishiduup) {
        this.penghukongqishiduup = penghukongqishiduup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column terminal_info.penghukongqiwenduDown
     *
     * @return the value of terminal_info.penghukongqiwenduDown
     *
     * @mbggenerated
     */
    public Double getPenghukongqiwendudown() {
        return penghukongqiwendudown;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column terminal_info.penghukongqiwenduDown
     *
     * @param penghukongqiwendudown the value for terminal_info.penghukongqiwenduDown
     *
     * @mbggenerated
     */
    public void setPenghukongqiwendudown(Double penghukongqiwendudown) {
        this.penghukongqiwendudown = penghukongqiwendudown;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column terminal_info.penghukongqiwenduUp
     *
     * @return the value of terminal_info.penghukongqiwenduUp
     *
     * @mbggenerated
     */
    public Double getPenghukongqiwenduup() {
        return penghukongqiwenduup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column terminal_info.penghukongqiwenduUp
     *
     * @param penghukongqiwenduup the value for terminal_info.penghukongqiwenduUp
     *
     * @mbggenerated
     */
    public void setPenghukongqiwenduup(Double penghukongqiwenduup) {
        this.penghukongqiwenduup = penghukongqiwenduup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column terminal_info.changquyuliangDown
     *
     * @return the value of terminal_info.changquyuliangDown
     *
     * @mbggenerated
     */
    public Double getChangquyuliangdown() {
        return changquyuliangdown;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column terminal_info.changquyuliangDown
     *
     * @param changquyuliangdown the value for terminal_info.changquyuliangDown
     *
     * @mbggenerated
     */
    public void setChangquyuliangdown(Double changquyuliangdown) {
        this.changquyuliangdown = changquyuliangdown;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column terminal_info.changquyuliangUp
     *
     * @return the value of terminal_info.changquyuliangUp
     *
     * @mbggenerated
     */
    public Double getChangquyuliangup() {
        return changquyuliangup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column terminal_info.changquyuliangUp
     *
     * @param changquyuliangup the value for terminal_info.changquyuliangUp
     *
     * @mbggenerated
     */
    public void setChangquyuliangup(Double changquyuliangup) {
        this.changquyuliangup = changquyuliangup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column terminal_info.changqufengsuDown
     *
     * @return the value of terminal_info.changqufengsuDown
     *
     * @mbggenerated
     */
    public Double getChangqufengsudown() {
        return changqufengsudown;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column terminal_info.changqufengsuDown
     *
     * @param changqufengsudown the value for terminal_info.changqufengsuDown
     *
     * @mbggenerated
     */
    public void setChangqufengsudown(Double changqufengsudown) {
        this.changqufengsudown = changqufengsudown;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column terminal_info.changqufengsuUp
     *
     * @return the value of terminal_info.changqufengsuUp
     *
     * @mbggenerated
     */
    public Double getChangqufengsuup() {
        return changqufengsuup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column terminal_info.changqufengsuUp
     *
     * @param changqufengsuup the value for terminal_info.changqufengsuUp
     *
     * @mbggenerated
     */
    public void setChangqufengsuup(Double changqufengsuup) {
        this.changqufengsuup = changqufengsuup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column terminal_info.changqufengliDown
     *
     * @return the value of terminal_info.changqufengliDown
     *
     * @mbggenerated
     */
    public Double getChangqufenglidown() {
        return changqufenglidown;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column terminal_info.changqufengliDown
     *
     * @param changqufenglidown the value for terminal_info.changqufengliDown
     *
     * @mbggenerated
     */
    public void setChangqufenglidown(Double changqufenglidown) {
        this.changqufenglidown = changqufenglidown;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column terminal_info.changqufengliUp
     *
     * @return the value of terminal_info.changqufengliUp
     *
     * @mbggenerated
     */
    public Double getChangqufengliup() {
        return changqufengliup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column terminal_info.changqufengliUp
     *
     * @param changqufengliup the value for terminal_info.changqufengliUp
     *
     * @mbggenerated
     */
    public void setChangqufengliup(Double changqufengliup) {
        this.changqufengliup = changqufengliup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column terminal_info.changqushiduDown
     *
     * @return the value of terminal_info.changqushiduDown
     *
     * @mbggenerated
     */
    public Double getChangqushidudown() {
        return changqushidudown;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column terminal_info.changqushiduDown
     *
     * @param changqushidudown the value for terminal_info.changqushiduDown
     *
     * @mbggenerated
     */
    public void setChangqushidudown(Double changqushidudown) {
        this.changqushidudown = changqushidudown;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column terminal_info.changqushiduUp
     *
     * @return the value of terminal_info.changqushiduUp
     *
     * @mbggenerated
     */
    public Double getChangqushiduup() {
        return changqushiduup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column terminal_info.changqushiduUp
     *
     * @param changqushiduup the value for terminal_info.changqushiduUp
     *
     * @mbggenerated
     */
    public void setChangqushiduup(Double changqushiduup) {
        this.changqushiduup = changqushiduup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column terminal_info.changquwenduDown
     *
     * @return the value of terminal_info.changquwenduDown
     *
     * @mbggenerated
     */
    public Double getChangquwendudown() {
        return changquwendudown;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column terminal_info.changquwenduDown
     *
     * @param changquwendudown the value for terminal_info.changquwenduDown
     *
     * @mbggenerated
     */
    public void setChangquwendudown(Double changquwendudown) {
        this.changquwendudown = changquwendudown;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column terminal_info.changquwenduUp
     *
     * @return the value of terminal_info.changquwenduUp
     *
     * @mbggenerated
     */
    public Double getChangquwenduup() {
        return changquwenduup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column terminal_info.changquwenduUp
     *
     * @param changquwenduup the value for terminal_info.changquwenduUp
     *
     * @mbggenerated
     */
    public void setChangquwenduup(Double changquwenduup) {
        this.changquwenduup = changquwenduup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column terminal_info.deviceSerial
     *
     * @return the value of terminal_info.deviceSerial
     *
     * @mbggenerated
     */
    public String getDeviceserial() {
        return deviceserial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column terminal_info.deviceSerial
     *
     * @param deviceserial the value for terminal_info.deviceSerial
     *
     * @mbggenerated
     */
    public void setDeviceserial(String deviceserial) {
        this.deviceserial = deviceserial == null ? null : deviceserial.trim();
    }
}