package com.example.nydp.entity;

import java.util.Date;

public class TerminalRunLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column terminalrunlog.runlogId
     *
     * @mbggenerated
     */
    private Long runlogid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column terminalrunlog.logGrade
     *
     * @mbggenerated
     */
    private String loggrade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column terminalrunlog.terminalId
     *
     * @mbggenerated
     */
    private Long terminalid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column terminalrunlog.terminalName
     *
     * @mbggenerated
     */
    private String terminalname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column terminalrunlog.eventType
     *
     * @mbggenerated
     */
    private String eventtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column terminalrunlog.detailed
     *
     * @mbggenerated
     */
    private String detailed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column terminalrunlog.createTime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column terminalrunlog.runlogId
     *
     * @return the value of terminalrunlog.runlogId
     *
     * @mbggenerated
     */
    public Long getRunlogid() {
        return runlogid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column terminalrunlog.runlogId
     *
     * @param runlogid the value for terminalrunlog.runlogId
     *
     * @mbggenerated
     */
    public void setRunlogid(Long runlogid) {
        this.runlogid = runlogid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column terminalrunlog.logGrade
     *
     * @return the value of terminalrunlog.logGrade
     *
     * @mbggenerated
     */
    public String getLoggrade() {
        return loggrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column terminalrunlog.logGrade
     *
     * @param loggrade the value for terminalrunlog.logGrade
     *
     * @mbggenerated
     */
    public void setLoggrade(String loggrade) {
        this.loggrade = loggrade == null ? null : loggrade.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column terminalrunlog.terminalId
     *
     * @return the value of terminalrunlog.terminalId
     *
     * @mbggenerated
     */
    public Long getTerminalid() {
        return terminalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column terminalrunlog.terminalId
     *
     * @param terminalid the value for terminalrunlog.terminalId
     *
     * @mbggenerated
     */
    public void setTerminalid(Long terminalid) {
        this.terminalid = terminalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column terminalrunlog.terminalName
     *
     * @return the value of terminalrunlog.terminalName
     *
     * @mbggenerated
     */
    public String getTerminalname() {
        return terminalname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column terminalrunlog.terminalName
     *
     * @param terminalname the value for terminalrunlog.terminalName
     *
     * @mbggenerated
     */
    public void setTerminalname(String terminalname) {
        this.terminalname = terminalname == null ? null : terminalname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column terminalrunlog.eventType
     *
     * @return the value of terminalrunlog.eventType
     *
     * @mbggenerated
     */
    public String getEventtype() {
        return eventtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column terminalrunlog.eventType
     *
     * @param eventtype the value for terminalrunlog.eventType
     *
     * @mbggenerated
     */
    public void setEventtype(String eventtype) {
        this.eventtype = eventtype == null ? null : eventtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column terminalrunlog.detailed
     *
     * @return the value of terminalrunlog.detailed
     *
     * @mbggenerated
     */
    public String getDetailed() {
        return detailed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column terminalrunlog.detailed
     *
     * @param detailed the value for terminalrunlog.detailed
     *
     * @mbggenerated
     */
    public void setDetailed(String detailed) {
        this.detailed = detailed == null ? null : detailed.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column terminalrunlog.createTime
     *
     * @return the value of terminalrunlog.createTime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column terminalrunlog.createTime
     *
     * @param createtime the value for terminalrunlog.createTime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}