package com.example.nydp.mapper;

import com.example.nydp.entity.RealTimeDateInfo;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

@Mapper
@Component
public interface RealTimeDateInfoMapper {

    int insertLog(RealTimeDateInfo info);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table realtimedateinfo
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long realtimeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table realtimedateinfo
     *
     * @mbggenerated
     */
    int insert(RealTimeDateInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table realtimedateinfo
     *
     * @mbggenerated
     */
    int insertSelective(RealTimeDateInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table realtimedateinfo
     *
     * @mbggenerated
     */
    RealTimeDateInfo selectByPrimaryKey(Long realtimeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table realtimedateinfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RealTimeDateInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table realtimedateinfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RealTimeDateInfo record);


    int updateKState(@Param("sbid") String sbid,@Param("state") String state,@Param("k") String k);
}