package com.example.nydp.mapper;

import com.example.nydp.entity.TerminalRunLog;

public interface TerminalRunLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terminalrunlog
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long runlogid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terminalrunlog
     *
     * @mbggenerated
     */
    int insert(TerminalRunLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terminalrunlog
     *
     * @mbggenerated
     */
    int insertSelective(TerminalRunLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terminalrunlog
     *
     * @mbggenerated
     */
    TerminalRunLog selectByPrimaryKey(Long runlogid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terminalrunlog
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TerminalRunLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terminalrunlog
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TerminalRunLog record);
}